---
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - "node_modules"
deploy:
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  provider: pages
  skip_cleanup: true
install:
  - npm install --ignore-scripts
language: node_js
node_js:
  - "lts/*"
notifications:
  webhooks: []
sudo: false
